# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='district')),
                ('order', models.CharField(blank=True, max_length=256, null=True, verbose_name='order')),
                ('event', models.CharField(blank=True, max_length=256, null=True, verbose_name='event')),
                ('piquetu', models.CharField(blank=True, max_length=256, null=True, verbose_name='piquetu')),
                ('plot', models.CharField(blank=True, max_length=256, null=True, verbose_name='plot')),
                ('rights_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='rights_14')),
                ('rights_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='rights_17')),
                ('cadastral_num_origin_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='cadastral_num_origin_14')),
                ('cadastral_num_origin_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='cadastral_num_origin_17')),
                ('origin_area_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='origin_area_17')),
                ('vac_area_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='vac_area_14')),
                ('vac_area_17', models.CharField(blank=True, max_length=256, null=True, verbose_name='vac_area_17')),
                ('category_origin', models.CharField(blank=True, max_length=256, null=True, verbose_name='category_origin')),
                ('obj_type_origin', models.CharField(blank=True, max_length=256, null=True, verbose_name='obj_type_origin')),
                ('cadastral_num_formed', models.CharField(blank=True, max_length=256, null=True, verbose_name='cadastral_num_formed')),
                ('provision_doc', models.CharField(blank=True, max_length=256, null=True, verbose_name='provision_doc')),
                ('requisites_dir_vac', models.CharField(blank=True, max_length=256, null=True, verbose_name='requisites_dir_vac')),
                ('requisites_assess', models.CharField(blank=True, max_length=256, null=True, verbose_name='requisites_assess')),
                ('obj_costat', models.CharField(blank=True, max_length=256, null=True, verbose_name='obj_costat')),
                ('offer_to_holdering', models.CharField(blank=True, max_length=256, null=True, verbose_name='offer_to_holdering')),
                ('requisites_agree_vac', models.CharField(blank=True, max_length=256, null=True, verbose_name='requisites_agree_vac')),
                ('pre_doc_transfer_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='pre_doc_transfer_type')),
                ('requisites_lease', models.CharField(blank=True, max_length=256, null=True, verbose_name='requisites_lease')),
                ('requisites_lease_agree', models.CharField(blank=True, max_length=256, null=True, verbose_name='requisites_lease_agree')),
                ('contacts_holder', models.CharField(blank=True, max_length=256, null=True, verbose_name='contacts_holder')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='comments')),
                ('form_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='form_area')),
                ('status_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='status_area')),
                ('rights_august_14', models.CharField(blank=True, max_length=256, null=True, verbose_name='rights_august_14')),
                ('pre_lang_plan', models.CharField(blank=True, max_length=256, null=True, verbose_name='pre_lang_plan')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attribute', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=256)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ht.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
