# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='district',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='district'),
        ),
    ]
