# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht', '0002_auto_20180327_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='attribute',
            field=models.CharField(max_length=256),
        ),
    ]
