# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht', '0003_auto_20180329_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='prov_doc_FDA',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Предоставление документов для подготовки распоряжения ФДА о предоставлении в аренду '),
        ),
        migrations.AlterField(
            model_name='feature',
            name='cadastral_num_formed',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Кадастровый номер образованного объекта недвижимости'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='cadastral_num_origin_14',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Кадастровый номер исходного объекта недвижимости ПМТ 2014'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='cadastral_num_origin_17',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Кадастровый номер исходного объкта недвижимости ПМТ 2017'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='category_origin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Категория исходного объекта недвижимости'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='contacts_holder',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Контакты правообладателя'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='district',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='event',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='form_area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Формирование земельных участков (кадастровый учет)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='obj_costat',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Стоимость объектов недвижимости'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='obj_type_origin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ВРИ исходного объекта недвижимости'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='offer_to_holdering',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Направление оферты правообладателю'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='№ п/п'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='origin_area_17',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь исходного объекта недвижимости, кв.м. ПМТ 2017'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='piquetu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пикет'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='plot',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='№ зу ПМТ'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='pre_doc_transfer_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Подготовка документов для перевода (отнесения) в категорию земель транспорта и/или изменение (установление) ВРИ'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='pre_lang_plan',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Подготовка межевого плана и передача его на кадастровый учет'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='provision_doc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Предоставление документов для подготовки распоряжения ФДА об изъятии'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='requisites_agree_vac',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты соглашения об изъятии '),
        ),
        migrations.AlterField(
            model_name='feature',
            name='requisites_assess',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты отчета об оценке'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='requisites_dir_vac',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты распоряжения об изъятии'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='requisites_lease',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты распоряжения о предоставлении в аренду'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='requisites_lease_agree',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Реквизиты договора аренды'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='rights_14',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Права ПМТ 2014'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='rights_17',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Права ПМТ 2017'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='rights_august_14',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Право после августа 2014'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status_area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Статус участка'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='vac_area_14',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь подлежащая изъятию, кв.м. ПМТ 2014'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='vac_area_17',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь подлежащая изъятию, кв.м. ПМТ 2017'),
        ),
    ]
